name: "accounts-service"

services:
    
  accounts-api:
    build:
      context: ./
      dockerfile: ./api_container/Dockerfile
    ports:
      - "${EXTERNAL_ACCOUNTS_API_PORT}:${ACCOUNTS_API_PORT}"
    restart: unless-stopped
    networks:
      - my-services-network
    environment:
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
    volumes:
      - ./shared_volume:${LOCAL_STORAGE_PATH}

volumes:
  accounts-local-storage:
    driver: local

networks:
  my-services-network:
    external: true
